name: Build OpenSSL Arm64

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      openssl_build:
        description: 'OpenSSL Arm64'
        required: false
        default: true
        type: boolean
      openssl_clang_build:
        description: 'OpenSSL with clang-cl Arm64'
        required: false
        default: true
        type: boolean

jobs:
  build-openssl-arm64:
    runs-on: [self-hosted, Windows, ARM64, GCC]
    timeout-minutes: 600

    steps:
    
    - name: Build OpenSSL Arm64
      shell: cmd
      run: |
        echo on
        rmdir /s /q openssl
        git clone https://github.com/openssl/openssl.git --single-branch --depth 1
        cd openssl
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" arm64
        set VSCMD_DEBUG=3
        set PATH=%PATH%;%VCINSTALLDIR%\Tools\Llvm\ARM64\bin
        perl Configure VC-WIN64-ARM
        nmake
        nmake test
        .\apps\openssl.exe speed 2> benchmark.txt
        type benchmark.txt

  build-openssl-clang-arm64:
    runs-on: [self-hosted, Windows, ARM64, GCC]
    timeout-minutes: 600

    steps:

    - name: Build OpenSSL with clang-cl Arm64
      shell: cmd
      run: |
        echo on
        rmdir /s /q openssl
        git clone https://github.com/openssl/openssl.git --single-branch --depth 1
        cd openssl
        call "%ProgramFiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" arm64
        set VSCMD_DEBUG=3
        set PATH=%PATH%;%VCINSTALLDIR%\Tools\Llvm\ARM64\bin
        perl Configure VC-CLANG-WIN64-CLANGASM-ARM
        nmake
        nmake test
        .\apps\openssl.exe speed 2> benchmark.txt
        type benchmark.txt

  build-openssl-aarch64:
    runs-on: [self-hosted, Linux, ARM64, GCC]
    timeout-minutes: 600

    steps:
    
    - name: Build OpenSSL Aarch64
      run: |
        [ -d openssl ] && rm -R openssl
        git clone https://github.com/openssl/openssl.git --single-branch --depth 1
        cd openssl
        ./Configure
        make
        make test
        LD_LIBRARY_PATH=$(pwd) apps/openssl speed > benchmark.txt 2>&1
        cat benchmark.txt
