name: Sync and validate master branch on Arm64 Windows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  sync-master:
    name: Sync master
    needs: validate-arm64-windows
    runs-on: ubuntu-latest

    steps:
      - run: gh repo sync Windows-on-ARM-Experiments/openssl -b master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-master-verification:
    name: Sync master-verification
    runs-on: ubuntu-latest

    steps:
      - run: gh repo sync Windows-on-ARM-Experiments/openssl -b master-verification
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-arm64-windows:
    name: Valitate the latest Arm64 Windows build
    needs: validate-arm64-windows
    uses: ./.github/workflows/ci-arm64.yml
    with:
      branch: master-verification
