name: New Valitate upstream master branch on Arm64 Windows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:

  validate-arm64-windows:
    runs-on: ubuntu-latest
    
    steps:
    - name: Getting upstream head hash
      run: echo "upstream_head_hash=$(git ls-remote https://github.com/openssl/openssl.git master | awk '{print $1}')" >> $GITHUB_ENV

    - name: Test
      run: echo $upstream_head_hash

    - name: Valitate upstream master Arm64 Windows build
      uses: Windows-on-ARM-Experiments/openssl/.github/workflows/ci-arm64.yml
      with:
        repository: openssl/openssl
        branch: ${{ env.upstream_head_hash }}
