name: New Valitate upstream master branch on Arm64 Windows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:

  get-upstream-head-hash:
    runs-on: ubuntu-latest
    outputs:
      upstream_head_hash: ${{ steps.get_upstream_hash.outputs.upstream_head_hash }}
\
    steps:
    - name: Getting upstream the head hash
      id: get_upstream_hash
      run: echo "upstream_head_hash=$(git ls-remote https://github.com/openssl/openssl.git master | awk '{print $1}')" >> "$GITHUB_OUTPUT"

  validate-arm64-windows:
    name: Valitate upstream master Arm64 Windows build
    needs: get-upstream-head-hash
    uses: ./.github/workflows/ci-arm64.yml
    with:
      repository: openssl/openssl
      branch: ${{ needs.get-upstream-head-hash.output.upstream_head_hash }}
